### PR TITLE
Update Portuguese translations

### PR DESCRIPTION
**Pull request by japakkjj**
§§a is the alternative color
§§m is the main color

### CODE REVIEW

**Comment by hampuskraft** [comment]
Thank you.

**Comment by japakkjj** [comment]
do you need to?(Keep as much color codes out of the locale files as possible§§a is the alternative color§§m is the main color) Enviado do Email para Windows De: Hampus KraftEnviado:terça-feira, 21 de fevereiro de 2023 14:39Para: NetherGamesMC/localeCc:japakkjj; AuthorAssunto: Re: [NetherGamesMC/locale] Update Portuguese translations (PR #22) Thank you.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by hampuskraft** [comment]
Pardon? You sent an entire CSS stylesheet in your previous reply.

**Comment by japakkjj** [comment]
because I'm trying to leave it the same as the other comments, without leaving that written update. Enviado do Email para Windows De: Hampus KraftEnviado:terça-feira, 21 de fevereiro de 2023 14:57Para: NetherGamesMC/localeCc:japakkjj; AuthorAssunto: Re: [NetherGamesMC/locale] Portuguese.json (PR #22) Pardon? You sent an entire CSS stylesheet in your previous reply.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by hampuskraft** [comment]
I unfortunately need to keep marking your comments as spam since you keep sending random garbage.

**Comment by hampuskraft** [comment]
Please use the GitHub UI to reply instead, since you appear to be doing something wrong when replying to the email.

**Comment by japakkjj** [comment]
but if I tell you the problem, do you solve it? Enviado do Email para Windows De: Hampus KraftEnviado:terça-feira, 21 de fevereiro de 2023 15:03Para: NetherGamesMC/localeCc:japakkjj; AuthorAssunto: Re: [NetherGamesMC/locale] Portuguese.json (PR #22) I unfortunately need to keep marking your comments as spam since you keep sending random garbage.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Pull request merged**
